{
 "title": "OpenAI Health",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Tokens</h1>"
   }
  },
  {
   "title": "Processed Prompt Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.COGNITIVESERVICES'\n| where MetricName == 'ProcessedPromptTokens'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Generated Completion Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.COGNITIVESERVICES'\n| where MetricName == 'GeneratedTokens'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Calls</h1>"
   }
  },
  {
   "title": "Total Model Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.COGNITIVESERVICES'\n| where MetricName == 'ModelRequests'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Successful Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.COGNITIVESERVICES'\n| where MetricName == 'SuccessfulCalls'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Average, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Operations</h1>"
   }
  },
  {
   "title": "Chat Comletion Create Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticLogs\n| where ResourceId contains 'MICROSOFT.COGNITIVESERVICES'\n| where OperationName == 'ChatCompletions_Create'\n| where $__timeFilter(Timestamp)\n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "List Key Operations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticLogs\n| where ResourceId contains 'MICROSOFT.COGNITIVESERVICES'\n| where OperationName == 'ListKey'\n| where $__timeFilter(Timestamp)\n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 30 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Latency</h1>"
   }
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DiagnosticMetrics\n| where ResourceId contains 'MICROSOFT.COGNITIVESERVICES'\n| where MetricName == 'Latency'\n| where $__timeFilter(Timestamp)\n| order by Timestamp desc\n| project-away Count, Total, Minimum, Maximum",
     "querySource": "raw"
    }
   ]
  }
 ]
}