{
 "title": "Chess Application Status",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Tokens</h1>"
   }
  },
  {
   "title": "Total Tokens",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body contains 'LLMCall'\n| extend TotalTokens = toint(parse_json(parse_json(parse_json(Body)['response'])['usage'])['total_tokens'])\n| summarize sum(TotalTokens)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Prompt VS Completion",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body contains 'LLMCall'\n| extend PromptTokens = toint(parse_json(Body)['prompt_tokens'])\n| extend CompletionTokens = toint(parse_json(Body)['completion_tokens'])\n| project PromptTokens, CompletionTokens\n| summarize sum(PromptTokens), sum(CompletionTokens)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tokens by Models",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body contains 'LLMCall'\n| extend Model = tostring(parse_json(parse_json(Body)['response'])['model'])\n| extend TotalTokens = toint(parse_json(parse_json(parse_json(Body)['response'])['usage'])['total_tokens'])\n| summarize sum(TotalTokens) by Model\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Models</h1>"
   }
  },
  {
   "title": "Actions by Model",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body contains 'LLMCall'\n| extend Model = tostring(parse_json(parse_json(Body)['response'])['model'])\n| summarize model_actions = count() by Model\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Open AI Services FQDN",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELMetrics\n| where $__timeFilter(Timestamp)\n| where MetricName == 'gen_ai.client.token.usage_sum'\n| extend ServerAddress = tostring(parse_json(MetricAttributes)['server.address'])\n| extend BaseServerAddress = extract(@\"(https://[^/]+)\", 1, ServerAddress)\n| distinct BaseServerAddress\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Agents</h1>"
   }
  },
  {
   "title": "Scores",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where SeverityText != ''\n| where Body contains 'Game Over'\n| extend Outcome = case(\n  Body has \"0-1\", \"0-1\",\n  Body has \"1-0\", \"1-0\",\n  Body has \"1/2-1/2\", \"1/2-1/2\",\n  Body has \"Unknown\", \"Unknown\",\n  \"Other\"\n)\n| summarize count() by Outcome\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "White Agent OpenAI Calls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body contains 'LLMCall' and Body contains 'You play WHITE'\n| count\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Black Agent OpenAI Calls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body contains 'LLMCall' and Body contains 'You play BLACK'\n| count\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 40 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">MCP</h1>"
   }
  },
  {
   "title": "MCP Tools Actions",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELTraces\n| where TraceAttributes contains \"gen_ai.completion.0.tool_calls.0.name\"\n| extend ToolName = tostring(parse_json(TraceAttributes)['gen_ai.completion.0.tool_calls.0.name'])\n| project ToolName\n| summarize count()by ToolName",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 52 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Content Filtering</h1>"
   }
  },
  {
   "title": "Hate filtered requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body contains 'LLMCall'\n| extend FilteredRequests = parse_json(parse_json(parse_json(parse_json(parse_json(parse_json(Body)['response'])['prompt_filter_results'])[0])['content_filter_results'])['hate'])['filtered']\n| where FilteredRequests == true\n| count\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Self Harm filtered requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body contains 'LLMCall'\n| extend FilteredRequests = parse_json(parse_json(parse_json(parse_json(parse_json(parse_json(Body)['response'])['prompt_filter_results'])[0])['content_filter_results'])['self_harm'])['filtered']\n| where FilteredRequests == true\n| count\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Sexual filtered requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body contains 'LLMCall'\n| extend FilteredRequests = parse_json(parse_json(parse_json(parse_json(parse_json(parse_json(Body)['response'])['prompt_filter_results'])[0])['content_filter_results'])['sexual'])['filtered']\n| where FilteredRequests == true\n| count\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Violence filtered requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where Body contains 'LLMCall'\n| extend FilteredRequests = parse_json(parse_json(parse_json(parse_json(parse_json(parse_json(Body)['response'])['prompt_filter_results'])[0])['content_filter_results'])['violence'])['filtered']\n| where FilteredRequests == true\n| count\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 61 },
   "options": {
    "content": "<h1 style=\"text-align: center; color: black;background-color:white\">Exceptions</h1>"
   }
  },
  {
   "title": "Total Info Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where SeverityText == 'INFO'\n| where ResourceAttributes != \"{}\"\n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Warning Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where SeverityText == 'WARN'\n| where ResourceAttributes != \"{}\"\n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Error Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where SeverityText == 'ERROR'\n| where ResourceAttributes != \"{}\"\n| count",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total INFO",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where SeverityText == 'INFO'\n| where ResourceAttributes != \"{}\"\n| order by Timestamp desc\n| extend CodeFilePath = tostring(LogsAttributes.['code.file.path'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function.name'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.line.number'])\n| project Timestamp, TraceID, SpanID, Body, CodeFilePath, CodeFunction, CodeLineNumber\n| take 100",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Warning",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where SeverityText == 'WARN'\n| where ResourceAttributes != \"{}\"\n| order by Timestamp desc\n| extend CodeFilePath = tostring(LogsAttributes.['code.file.path'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function.name'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.line.number'])\n| project Timestamp, TraceID, SpanID, Body, CodeFilePath, CodeFunction, CodeLineNumber\n| take 100",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total ERRORS",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "database": "openteldb",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "OTELLogs\n| where $__timeFilter(Timestamp)\n| where SeverityText == 'ERROR'\n| where ResourceAttributes != \"{}\"\n| order by Timestamp desc\n| extend CodeFilePath = tostring(LogsAttributes.['code.file.path'])\n| extend CodeFunction = tostring(LogsAttributes.['code.function.name'])\n| extend CodeLineNumber = tostring(LogsAttributes.['code.line.number'])\n| project Timestamp, TraceID, SpanID, Body, CodeFilePath, CodeFunction, CodeLineNumber\n| take 100",
     "querySource": "raw"
    }
   ]
  }
 ]
}